### ISSUE TITLE
Unhandled Promise Rejection on Agent Startup

### ISSUE THREAD

**Issue by saschagoebel** [graphprotocol/indexer#184]
Every time my Agent Docker-Container (graphprotocol/indexer-agent:sha-4d50de5) starts, I get this error:

```json
{
    "level": 40,
    "time": 1609778087715,
    "pid": 1,
    "hostname": "2080bef9d9ee",
    "name": "IndexerAgent",
    "err": {
        "type": "IndexerError",
        "message": "Unhandled promise rejection",
        "stack": "IndexerError: Unhandled promise rejection\n    at Object.indexerError (/opt/indexer/packages/indexer-common/dist/errors.js:97:12)\n    at process.<anonymous> (/opt/indexer/packages/indexer-agent/dist/commands/start.js:212:39)\n    at process.emit (events.js:321:20)\n    at process.EventEmitter.emit (domain.js:482:12)\n    at processPromiseRejections (internal/process/promises.js:209:33)\n    at processTicksAndRejections (internal/process/task_queues.js:98:32)",
        "code": "IE035",
        "explanation": "https://github.com/graphprotocol/indexer/blob/master/docs/errors.md#ie035",
        "cause": {
            "type": "Error",
            "message": "call revert exception (method=\"getReserves()\", errorSignature=null, errorArgs=[null], reason=null, code=CALL_EXCEPTION, version=abi/5.0.9)",
            "stack": "Error: call revert exception (method=\"getReserves()\", errorSignature=null, errorArgs=[null], reason=null, code=CALL_EXCEPTION, version=abi/5.0.9)\n    at Logger.makeError (/opt/indexer/node_modules/@ethersproject/logger/lib/index.js:179:21)\n    at Logger.throwError (/opt/indexer/node_modules/@ethersproject/logger/lib/index.js:188:20)\n    at Interface.decodeFunctionResult (/opt/indexer/node_modules/@ethersproject/abi/lib/interface.js:286:23)\n    at Contract.<anonymous> (/opt/indexer/node_modules/@ethersproject/contracts/lib/index.js:319:56)\n    at step (/opt/indexer/node_modules/@ethersproject/contracts/lib/index.js:46:23)\n    at Object.next (/opt/indexer/node_modules/@ethersproject/contracts/lib/index.js:27:53)\n    at fulfilled (/opt/indexer/node_modules/@ethersproject/contracts/lib/index.js:18:58)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
            "reason": null,
            "code": "CALL_EXCEPTION",
            "method": "getReserves()",
            "errorSignature": null,
            "errorArgs": [null],
            "address": "0x588E0e70a7565552300C19F59155d0Cf21065fBA",
            "args": [],
            "transaction": {
                "data": "0x0902f1ac",
                "to": "0x588E0e70a7565552300C19F59155d0Cf21065fBA"
            }
        }
    },
    "msg": "Unhandled promise rejection"
}
```

The call fails for the obvious reason that this address is not a contract on Mainnet (or Rinkeby or Ropsten).

The Agent keeps running, but never fetches the $DAI variable, which may or may not be related. As Node tends to ignore code paths once an unhandled rejection occurs, I'd guess this is somewhere on the $DAI fetching path.

**Comment by Jannis** [comment]
@saschagoebel What version of indexer-agent are you running?

**Comment by saschagoebel** [comment]
@Jannis graphprotocol/indexer-agent:sha-4d50de5 which is 0.9.0-alpha.2

I updated my testnet scripts, so I don't think there are any obvious mistakes. Only difference are the config changes as noted in the ReadMe (https://github.com/graphprotocol/mission-control-indexer) and I'm using an operator account now, so the mnemonic is for the operator and the address points to my lock contract.

Is there a newer docker image I can (semi safely) try?

**Comment by saschagoebel** [comment]
Docker-Compose:
```yaml
thegraph-indexer-agent:
    image: graphprotocol/indexer-agent:sha-4d50de5
    command: "--indexer-geo-coordinates=49.460983 11.061859 --inject-dai"
    environment:
      INDEXER_AGENT_ETHEREUM: http://jsonrpc.ethereum.ethereum.mainnet.parity.archive-node-0032/
      INDEXER_AGENT_ETHEREUM_NETWORK: mainnet
      INDEXER_AGENT_MNEMONIC: some funny words that make up a secret phrase
      INDEXER_AGENT_INDEXER_ADDRESS: "0x..."
      INDEXER_AGENT_INDEXER_GEO_COORDINATES: 49.460983 11.061859
      INDEXER_AGENT_INDEX_NODE_IDS: thegraph_index_0001
      INDEXER_AGENT_GRAPH_NODE_QUERY_ENDPOINT: http://xxx:8000
      INDEXER_AGENT_GRAPH_NODE_STATUS_ENDPOINT: http://yyy:8030/graphql
      INDEXER_AGENT_GRAPH_NODE_ADMIN_ENDPOINT: http://yyy:8020
      INDEXER_AGENT_NETWORK_SUBGRAPH_ENDPOINT: https://gateway.network.thegraph.com/network
      INDEXER_AGENT_PUBLIC_INDEXER_URL: https://indexer.thegraph.anyblock.net/
      INDEXER_AGENT_INDEXER_MANAGEMENT_PORT: 8000
      INDEXER_AGENT_POSTGRES_HOST: zzz
      INDEXER_AGENT_POSTGRES_PORT: 5432
      INDEXER_AGENT_POSTGRES_DATABASE: indexer-agent
      INDEXER_AGENT_POSTGRES_USERNAME: secret
      INDEXER_AGENT_POSTGRES_PASSWORD: changeme
      INDEXER_AGENT_INJECT_DAI: "true"
      INDEXER_AGENT_DAI_CONTRACT: "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48"
    extra_hosts:
      - jsonrpc.ethereum.ethereum.mainnet.parity.archive-node-0001:aaa
      - jsonrpc.ethereum.ethereum.mainnet.parity.archive-node-0032:bbb
    ports:
      - "8888:8000"
      - "7302:7300"
    network_mode: bridge
    restart: unless-stopped
```
