### ISSUE TITLE
Different hash with Ropsten chain at block 8482468

### ISSUE THREAD

**Issue by fewensa** [graphprotocol/indexer#379]
Hi. 
I'm using hosted-server to index Ropsten chain. I found a question. in Ropsten chain theGraph hosted-server queried hash is `0xc418ed0f89d94c29e055c472230448c98189a05f87e776b68ee8226025cdc60f` at block `8482468` is not same in Ropsten etherscan `0x5b778af10645c9aece0cceb69d2e1b9942eb71b11acbe393a371db4919cee1a8`  https://ropsten.etherscan.io/block/8482468

**Comment by fordN** [comment]
Hey @fewensa 👋  

This type of hosted-service data issue is typically best reported in the graphprotocl discord server. However, I'm happy to help you debug here this time. 

Could you provide some more context on the data you shared? I'm not seeing the same data integrity problem you reported on the hosted-service. For instance, if you query the [blocklytics/ropsten-blocks](https://thegraph.com/hosted-service/subgraph/blocklytics/ropsten-blocks) subgraph you'll the data matches what's on [etherscan](https://ropsten.etherscan.io/block/8482468):

- query
    ```graphql
    {
      blocks (
        where:{
          number:8482468
        }
      ) {
        id
        number   
        parentHash
        gasUsed
        gasLimit
        difficulty
        totalDifficulty
        size
        stateRoot
      }
    }
    ```

- response
    ```graphql
    {
      "data": {
        "blocks": [
          {
            "id": "0x5b778af10645c9aece0cceb69d2e1b9942eb71b11acbe393a371db4919cee1a8",
            "number": "8482468",
            "parentHash": "0x0ffd7427b473a250baa97f2ca5924331c1e709f491553d2c5fb399f6f736abc4",
            "gasUsed": "7598296",
            "gasLimit": "8000000",
            "difficulty": "572780990",
            "totalDifficulty": "31291797846198240",
            "size": "12821",
            "stateRoot": "0xbc123e0d8977a4938131daeae8651bca543b66b5615c6d639354ef8788087b37"
          }
        ]
      }
    }
    ```

Where did you get the Ropsten block data from the hosted-service that you shared (hash: `0xc418ed0f89d94c29e055c472230448c98189a05f87e776b68ee8226025cdc60f`, number :`8482468`)?

**Comment by xiaoch05** [comment]
Hi @fordN , I write a test subgraph as follows
schema.graphql
```
type NodeEntity @entity {
  id: ID! #id is a required field
  position: String!
  hash: Bytes!
}
```

subgraph.yaml
```
specVersion: 0.0.2
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum/contract
    name: mmr
    network: ropsten
    source:
      address: "0x0000000000000000000000000000000000000000"
      abi: mmr
      startBlock: 8482460
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.4
      language: wasm/assemblyscript
      entities:
        - Test
      abis:
        - name: mmr
          file: ./abis/mmr.json
      eventHandlers:
        - event: Test(address)
          handler: handleTest
      blockHandlers:
        - handler: handleBlock
      file: ./src/mapping.ts
```

mapping.ts
```
import { mmr, Test } from "../generated/mmr/mmr"
import { NodeEntity } from "../generated/schema"
import { ethereum } from '@graphprotocol/graph-ts'

export function handleTest(event: Test): void {
}

export function handleBlock(block: ethereum.Block): void {
    let record = new NodeEntity(block.number.toString());
    record.position = block.number.toString();
    record.hash = block.hash;
    record.save();
}

```

and deploy the subgraph at 
https://thegraph.com/hosted-service/subgraph/xiaoch05/blockhash

and I query the blockhash, the response is
```
      {
        "id": "8482466",
        "position": "8482466",
        "hash": "0x9834f01bace1ed7e88c015bb34d8fc69107471d251245aed0039d6ad630b2fef"
      },
      {
        "id": "8482467",
        "position": "8482467",
        "hash": "0x0ffd7427b473a250baa97f2ca5924331c1e709f491553d2c5fb399f6f736abc4"
      },
      {
        "id": "8482468",
        "position": "8482468",
        "hash": "0xc418ed0f89d94c29e055c472230448c98189a05f87e776b68ee8226025cdc60f"
      },
      {
        "id": "8482469",
        "position": "8482469",
        "hash": "0x2f11f1b9d69613c849426c32105dff0ed1ec00bd5af9bf585054f5ebe17f4217"
      }
```
we get the wrong blockhash at block 8482468 and block 8482469
