### ISSUE TITLE
old and new environment variables for postgres are needed

### ISSUE THREAD

**Issue by czarly** [graphprotocol/indexer#78]
starting up the indexer-service without postgres-host is throwing errors because that argument is required. I'm using environment variables, so I set the INDEXER_SERVICE_POSTGRES_HOST to my hostname. That resolves the issue with the error message but the the indexer service tries to connect to postgres on 127.0.0.1 instead of the indicated host.

this led me to try to keep the old variables set and adding the old variables back in addition to the new variables silenced the error message for missing parameters and established a connection to the database.

this is the relevant part of my docker-compose.yml of the working configuration. removing SERVER_HOST will let it connect to localhost, removing INDEXER_SERVICE_POSTGRES_HOST will make the service complain on startup.

```
indexer-service:
    image: graphprotocol/indexer-service:sha-01598d1
    container_name: indexer-service
    depends_on: 
      - index-node
    environment:
      INDEXER_SERVICE_MNEMONIC: ${WALLET_SEED_PHRASE}
      INDEXER_SERVICE_INDEXER_ADDRESS: ${WALLET_ADDRESS}
      INDEXER_SERVICE_PORT: 7600
      INDEXER_SERVICE_ETHEREUM: https://rinkeby.infura.io/v3/${INFURA_PROJECT_ID}
      INDEXER_SERVICE_GRAPH_NODE_QUERY_ENDPOINT: http://query-node:8000
      INDEXER_SERVICE_GRAPH_NODE_STATUS_ENDPOINT: http://index-node:8030/graphql
      INDEXER_SERVICE_NETWORK_SUBGRAPH_ENDPOINT: https://api.thegraph.com/subgraphs/name/graphprotocol/graph-network-testnet-phase2
      INDEXER_SERVICE_POSTGRES_HOST: postgres2
      INDEXER_SERVICE_POSTGRES_USERNAME: ${DB_USER:-graph-node}
      INDEXER_SERVICE_POSTGRES_PASSWORD: ${DB_PASS:-let-me-in}
      INDEXER_SERVICE_POSTGRES_DATABASE: ${AGENT_DB_NAME:-indexer-agent}
      SERVER_HOST: postgres2
      SERVER_PORT: 5432
      SERVER_DB_USER: ${DB_USER:-graph-node}
      SERVER_DB_PASSWORD: ${DB_PASS:-let-me-in}
      SERVER_DB_NAME: ${AGENT_DB_NAME:-indexer-agent}
      VIRTUAL_HOST: ${INDEX_HOST}
      VIRTUAL_PORT: 7600
      LETSENCRYPT_HOST: ${INDEX_HOST}
    expose:
      - 7600
      - 7300
    networks:
      - monitor-net
    restart: unless-stopped
```
